// Level definitions
export const LEVELS = [
  {
    id: 0,
    name: "Day 1",
    subtitle: "Sunny Meadow",
    atmosphere: "day",
    bgKey: "bg_day",
    music: "music_grasswalk",
    startSun: 150,
    maxWaves: 3,
    unlockPlants: ["snowpea"],
    waves: [
      [{ type:"regular", count:3, rows:[0,2,4] }],
      [{ type:"regular", count:3, rows:[0,1,3] }, { type:"cone", count:1, rows:[2] }],
      [{ type:"cone", count:2, rows:[1,3] }, { type:"regular", count:3, rows:[0,2,4] }, { type:"flag", count:1, rows:[0] }],
    ],
  },
  {
    id: 1,
    name: "Night 2",
    subtitle: "Moonlit Garden",
    atmosphere: "night",
    bgKey: "bg_night",
    music: "music_moongrains",
    startSun: 75,
    maxWaves: 4,
    unlockPlants: ["repeater"],
    waves: [
      [{ type:"regular", count:4, rows:[0,1,2,3] }],
      [{ type:"cone", count:2, rows:[0,4] }, { type:"regular", count:3, rows:[1,2,3] }],
      [{ type:"bucket", count:1, rows:[2] }, { type:"cone", count:2, rows:[0,4] }, { type:"regular", count:3, rows:[1,3,2] }],
      [{ type:"bucket", count:2, rows:[1,3] }, { type:"flag", count:1, rows:[0] }, { type:"regular", count:4, rows:[0,2,4,1] }],
    ],
  },
  {
    id: 2,
    name: "Pool 3",
    subtitle: "Watery Depths",
    atmosphere: "pool",
    bgKey: "bg_pool",
    music: "music_watery_graves",
    startSun: 150,
    maxWaves: 5,
    unlockPlants: ["chomper"],
    waves: [
      [{ type:"regular", count:4, rows:[0,1,3,4] }],
      [{ type:"cone", count:3, rows:[1,2,3] }, { type:"regular", count:2, rows:[0,4] }],
      [{ type:"bucket", count:2, rows:[0,4] }, { type:"regular", count:3, rows:[1,2,3] }],
      [{ type:"football", count:1, rows:[2] }, { type:"cone", count:3, rows:[0,2,4] }, { type:"regular", count:3, rows:[1,3,1] }],
      [{ type:"football", count:2, rows:[1,3] }, { type:"bucket", count:2, rows:[0,4] }, { type:"flag", count:1, rows:[2] }, { type:"regular", count:4, rows:[0,1,2,3] }],
    ],
  },
  {
    id: 3,
    name: "Fog 4",
    subtitle: "Misty Cemetery",
    atmosphere: "fog",
    bgKey: "bg_fog",
    music: "music_cerebrawl",
    startSun: 100,
    maxWaves: 5,
    unlockPlants: ["iceshroom"],
    waves: [
      [{ type:"newspaper", count:3, rows:[0,2,4] }],
      [{ type:"cone", count:3, rows:[1,2,3] }, { type:"newspaper", count:2, rows:[0,4] }],
      [{ type:"bucket", count:2, rows:[0,4] }, { type:"football", count:1, rows:[2] }],
      [{ type:"football", count:2, rows:[1,3] }, { type:"bucket", count:2, rows:[0,4] }, { type:"cone", count:3, rows:[0,2,4] }],
      [{ type:"gargantuar", count:1, rows:[2] }, { type:"football", count:2, rows:[1,3] }, { type:"flag", count:1, rows:[0] }, { type:"regular", count:5, rows:[0,1,2,3,4] }],
    ],
  },
  {
    id: 4,
    name: "Roof 5",
    subtitle: "Final Stand",
    atmosphere: "roof",
    bgKey: "bg_roof",
    music: "music_cerebrawl",
    startSun: 125,
    maxWaves: 6,
    unlockPlants: ["squash", "tallnut"],
    waves: [
      [{ type:"football", count:2, rows:[1,3] }, { type:"regular", count:3, rows:[0,2,4] }],
      [{ type:"gargantuar", count:1, rows:[2] }, { type:"bucket", count:2, rows:[0,4] }, { type:"cone", count:2, rows:[1,3] }],
      [{ type:"football", count:2, rows:[1,3] }, { type:"newspaper", count:3, rows:[0,2,4] }],
      [{ type:"gargantuar", count:2, rows:[1,3] }, { type:"football", count:2, rows:[0,4] }, { type:"bucket", count:3, rows:[0,2,4] }],
      [{ type:"imp", count:6, rows:[0,1,2,3,4,2] }, { type:"gargantuar", count:2, rows:[0,4] }],
      [{ type:"gargantuar", count:3, rows:[0,2,4] }, { type:"football", count:2, rows:[1,3] }, { type:"flag", count:1, rows:[2] }, { type:"regular", count:5, rows:[0,1,2,3,4] }],
    ],
  },
];
